### ISSUE TITLE
모델이 점점 산으로 가요,,,

### ISSUE THREAD

**Issue by sjnam95** [2021-SMHRD-KDT-AI-4/Alcohol-Free#35]
- [x] 정답률은 올랐으나, 실제 데이터를 넣어 보았을 때 모두 Neutral로 인식하는 문제 발생

**Comment by xoxo950** [comment]
학습때 사용했던 데이터셋 구축 클래스 활용 테스트 실시 결과 문제 없음
예측용으로 만든 데이터셋 구축 클래스가 문제가 있을것으로 생각됨
